// ============================================================
// 2024 新版 PEP 五年级上册 完整词汇数据集
// 来源：官方教材词汇表（黑体词 + 白体词）
// 共 6 单元，约 112 个单词
// 带 * 为课标二级必掌握词汇（黑体词/四会词）
// 包含：英文、中文释义、Emoji、记忆小贴士、单元归属
// ============================================================

const VOCABULARY_DATA = [
  // ==================== Unit 1: Different Friends 不一样的朋友 ====================
  { en:"team", zh:"（游戏或运动的）队；（一起工作的）组，班", emoji:"👥", tip:"team = 团队！T 像队长领队，大家一起 team work！", unit:1 },
  { en:"player", zh:"运动员；参赛选手", emoji:"⛹️", tip:"play（玩/比赛）+ er = player（运动员）！打球的人~", unit:1 },
  { en:"him", zh:"他（宾格）", emoji:"👦", tip:"him 是他（宾格），和 he（主格）是兄弟词！I like him~", unit:1, required:true },
  { en:"lovely", zh:"美丽的；优美的", emoji:"🌸", tip:"love（爱）+ ly = lovely（可爱的、美丽的），让你忍不住喜欢！", unit:1, required:true },
  { en:"clever", zh:"聪明的；聪颖的", emoji:"🧠", tip:"clever = 聪明！读音像'可乐我'→ 喝可乐变聪明~", unit:1, required:true },
  { en:"young", zh:"幼小的；年轻的", emoji:"👶", tip:"young = 年轻，和 old（老）相反！一起记：young ↔ old", unit:1, required:true },
  { en:"hard-working", zh:"工作努力的；辛勤的", emoji:"💪", tip:"hard（努力）+ working（工作）= 努力工作的！拆开超好记！", unit:1 },
  { en:"science", zh:"科学；自然科学", emoji:"🔬", tip:"science = 科学！读音像'赛恩斯'→ 科学比赛~", unit:1, required:true },
  { en:"robot", zh:"机器人", emoji:"🤖", tip:"robot = 机器人！发音就是'机器人'的英文版！", unit:1, required:true },
  { en:"jump", zh:"跳；跃", emoji:"🦘", tip:"jump = 跳！想象袋鼠 jump jump jump！", unit:1, required:true },
  { en:"rope", zh:"绳；粗绳", emoji:"🪢", tip:"rope = 绳子，和 hope（希望）差一个字母！跳绳→ jump rope！", unit:1, required:true },
  { en:"piano", zh:"钢琴", emoji:"🎹", tip:"piano = 钢琴，三个音节 pi-a-no，弹钢琴→ play the piano！", unit:1 },
  { en:"chess", zh:"国际象棋", emoji:"♟️", tip:"chess = 国际象棋，和 dress（裙子）押韵！下棋→ play chess~", unit:1 },
  { en:"front", zh:"前部", emoji:"⬆️", tip:"front = 前面，和 back（后面）相反！in front of = 在…前面~", unit:1, required:true },
  { en:"easy", zh:"容易的；轻易的", emoji:"👍", tip:"easy = 简单！读音像'一贼'→ 简单得像只有一个贼~", unit:1, required:true },
  { en:"star", zh:"歌唱（或表演）明星", emoji:"⭐", tip:"star = 星星 / 明星！天上的星星和舞台上的明星都是 star~", unit:1, required:true },
  { en:"wonderful", zh:"精彩的；绝妙的", emoji:"🎉", tip:"wonder（奇迹）+ ful = wonderful！太精彩了像奇迹一样！", unit:1, required:true },
  { en:"Australia", zh:"澳大利亚", emoji:"🦘", tip:"Australia = 澳大利亚，袋鼠的家乡！首字母 A 大写~", unit:1 },

  // ==================== Unit 2: My Feelings 我的情绪 ====================
  { en:"sad", zh:"悲哀的；难过的", emoji:"😢", tip:"sad 只有三个字母，像下雨天的心情~和 happy 相反！", unit:2, required:true },
  { en:"matter", zh:"事情；问题", emoji:"❓", tip:"matter = 事情，What's the matter? = 怎么了？关心别人的常用句~", unit:2 },
  { en:"project", zh:"项目；方案", emoji:"📋", tip:"project = 项目/课题，学校常做的 project 作业~", unit:2 },
  { en:"centre", zh:"中心", emoji:"🎯", tip:"centre = 中心！英式拼法，美式拼 center~", unit:2 },
  { en:"agree", zh:"同意；赞成", emoji:"🤝", tip:"agree = 同意，disagree = 不同意！a-gree 两个音节~", unit:2 },
  { en:"finish", zh:"完成；做好", emoji:"✅", tip:"finish = 完成！做完了就喊'I finish!'~", unit:2 },
  { en:"Monday", zh:"星期一", emoji:"📅", tip:"Monday = 周一，Mon = 月亮 day~ 一周的开始！", unit:2 },
  { en:"worried", zh:"担心的；担忧的", emoji:"😟", tip:"worried 来自 worry（担心），把 y 变 i 加 ed~", unit:2 },
  { en:"both", zh:"两者", emoji:"✌️", tip:"both = 两者都！both A and B = A 和 B 都~", unit:2 },
  { en:"excited", zh:"激动的；兴奋的", emoji:"🤩", tip:"excite（兴奋）+ d = excited！像过生日拆礼物一样兴奋！", unit:2, required:true },
  { en:"wrong", zh:"错误的", emoji:"❌", tip:"wrong = 错，和 right（对）相反！一起记：right ↔ wrong", unit:2, required:true },
  { en:"angry", zh:"愤怒的；生气的", emoji:"😠", tip:"angry 音似'暗鬼'→ 生气得像暗黑小鬼！别惹 Ta~", unit:2, required:true },
  { en:"afraid", zh:"担心；害怕", emoji:"😨", tip:"afraid = 害怕，be afraid of = 害怕… 胆子小的时候就 afraid~", unit:2 },
  { en:"parent", zh:"父亲；母亲", emoji:"👨‍👩‍👧", tip:"parent = 父母，爸爸妈妈都是 parent！复数→ parents~", unit:2, required:true },
  { en:"ask", zh:"问；询问", emoji:"🙋", tip:"ask = 问！只有三个字母，不懂就 ask！", unit:2, required:true },
  { en:"move", zh:"搬家；移动", emoji:"📦", tip:"move = 移动/搬家，看电影 move 起来！", unit:2, required:true },
  { en:"yours", zh:"您的（用于书信结尾签名前）", emoji:"💌", tip:"yours = 你的（名词性物主代词），书信结尾写 Yours~", unit:2 },

  // ==================== Unit 3: Work and Play 学习与玩乐 ====================
  { en:"Wednesday", zh:"星期三", emoji:"📅", tip:"Wednesday = 周三！拼写难：We-d-nes-day 分四段记！", unit:3 },
  { en:"subject", zh:"科目；学科", emoji:"📚", tip:"subject = 学科！sub + ject，学校里学的科目~", unit:3, required:true },
  { en:"Monday", zh:"星期一", emoji:"📅", tip:"Monday = 周一（Unit2 也出现了哦~）Mon-day！", unit:3 },
  { en:"Tuesday", zh:"星期二", emoji:"📅", tip:"Tuesday = 周二！Tues-day，Two 的发音有点像 Tues~", unit:3 },
  { en:"Friday", zh:"星期五", emoji:"🎉", tip:"Friday = 周五！Fri-day，周五最开心！TGIF！", unit:3 },
  { en:"because", zh:"因为", emoji:"🤔", tip:"because = 因为，be-cause 两个音节，回答 why 用 because！", unit:3, required:true },
  { en:"Thursday", zh:"星期四", emoji:"📅", tip:"Thursday = 周四！Thurs-day，最难拼的星期词~", unit:3 },
  { en:"start", zh:"开始", emoji:"▶️", tip:"start = 开始，和 finish 相反！Let's start! 我们开始吧！", unit:3 },
  { en:"usually", zh:"通常地；经常地", emoji:"🔄", tip:"usually = 通常，usual（平常）+ ly，和平常一样~", unit:3 },
  { en:"weekend", zh:"周末", emoji:"🎊", tip:"weekend = 周末！week（周）+ end（末尾）= 一周的末尾~", unit:3 },
  { en:"sometimes", zh:"有时；间或", emoji:"🕐", tip:"some（一些）+ times（时候）= 有时候！拆开超好记！", unit:3, required:true },
  { en:"Saturday", zh:"星期六", emoji:"🎮", tip:"Saturday = 周六！Satur-day，周末第一天！", unit:3 },
  { en:"Sunday", zh:"星期日", emoji:"☀️", tip:"Sunday = 周日！Sun-day，太阳日，一周的最后一天~", unit:3 },
  { en:"lesson", zh:"课；一节课", emoji:"🏫", tip:"lesson = 课，和 class 是近义词！上英语课→ English lesson~", unit:3, required:true },
  { en:"evening", zh:"晚上；傍晚", emoji:"🌆", tip:"evening = 晚上/傍晚，太阳下山了就是 evening！", unit:3, required:true },
  { en:"answer", zh:"答复；回答", emoji:"💬", tip:"answer = 回答，question（问题）的搭档！问和答：question & answer", unit:3, required:true },
  { en:"ping-pong", zh:"乒乓球", emoji:"🏓", tip:"ping-pong = 乒乓球！就是中文'乒乓'的音译！", unit:3, required:true },
  { en:"night", zh:"夜；夜晚", emoji:"🌙", tip:"night = 夜晚，和 day（白天）相反！Good night！晚安~", unit:3, required:true },
  { en:"visit", zh:"看望；拜访；参观", emoji:"🏠", tip:"visit = 拜访/参观，visit grandparents = 看望爷爷奶奶~", unit:3, required:true },
  { en:"grandparent", zh:"祖父；祖母；外祖父；外祖母", emoji:"👴👵", tip:"grand（伟大的）+ parent（父母）= grandparent 祖父母！", unit:3 },

  // ==================== Unit 4: Healthy Habits 健康习惯 ====================
  { en:"stay", zh:"待；保持；继续是", emoji:"🏠", tip:"stay = 待着/保持，stay healthy = 保持健康！", unit:4 },
  { en:"should", zh:"（提建议）该，可以", emoji:"💡", tip:"should = 应该！You should... = 你应该… 给建议的万能词！", unit:4, required:true },
  { en:"flu", zh:"流行性感冒；流感", emoji:"🤒", tip:"flu = 流感！只有三个字母，感冒了要 have a rest~", unit:4 },
  { en:"else", zh:"其他的；别的", emoji:"🔀", tip:"else = 其他的！What else? = 还有什么？常用小词~", unit:4 },
  { en:"exercise", zh:"锻炼；训练；操练", emoji:"🏃", tip:"exercise = 锻炼！音似'艾克斯赛斯'→ 像赛车一样动起来！", unit:4, required:true },
  { en:"enough", zh:"足够的；充足的；充分的", emoji:"✅", tip:"enough = 足够，e-nough，够用就好！sleep enough = 睡够~", unit:4 },
  { en:"if", zh:"如果；假若；倘若", emoji:"🤔", tip:"if = 如果！只有两个字母，假设句型必备！", unit:4 },
  { en:"habit", zh:"习惯", emoji:"🔄", tip:"habit = 习惯，good habit 好习惯 / bad habit 坏习惯！", unit:4 },
  { en:"show", zh:"（电视或广播）节目", emoji:"📺", tip:"show = 节目/表演，TV show = 电视节目！", unit:4, required:true },
  { en:"phone", zh:"电话；电话机", emoji:"📱", tip:"phone = 电话！mobile phone = 手机~", unit:4, required:true },
  { en:"then", zh:"那么；因此；既然如此", emoji:"👉", tip:"then = 那么/然后，只有四个字母！First... then... 先说再做~", unit:4, required:true },
  { en:"rest", zh:"休息；放松", emoji:"😴", tip:"rest = 休息，have a rest = 休息一下！", unit:4 },
  { en:"take care of", zh:"爱护；照顾", emoji:"🤲", tip:"take care of = 照顾！Take care of yourself = 照顾好自己~", unit:4 },
  { en:"check", zh:"查看；查明", emoji:"🔍", tip:"check = 检查！check your work = 检查你的作业~", unit:4 },
  { en:"less", zh:"较少的，更少的（修饰不可数名词）", emoji:"📉", tip:"less = 更少，和 more（更多）相反！", unit:4 },
  { en:"brush", zh:"（用刷子）刷净，刷亮", emoji:"🪥", tip:"brush = 刷！brush your teeth = 刷牙！", unit:4 },
  { en:"tooth", zh:"牙；齿（复数 teeth）", emoji:"🦷", tip:"tooth = 牙齿，复数 teeth！brush your teeth 每天两次~", unit:4 },
  { en:"twice", zh:"两次；两遍", emoji:"✌️", tip:"twice = 两次！two → twice，和 once（一次）一起记！", unit:4 },
  { en:"hour", zh:"小时", emoji:"⏰", tip:"hour = 小时，h 不发音！an hour = 一个小时~", unit:4, required:true },
  { en:"free", zh:"空闲的；无安排的", emoji:"🕊️", tip:"free = 空闲/自由！I'm free = 我有空~", unit:4, required:true },

  // ==================== Unit 5: Food We Eat 我们吃的食物 ====================
  { en:"hungry", zh:"感到饿的", emoji:"😋", tip:"hungry = 饿！饿得像'夯个梨'来吃！I'm hungry~", unit:5, required:true },
  { en:"beef", zh:"牛肉", emoji:"🥩", tip:"beef = 牛肉！bee（蜜蜂）+ f → 蜜蜂飞到牛肉上？记住画面！", unit:5 },
  { en:"ice cream", zh:"（一份）冰激凌", emoji:"🍦", tip:"ice（冰）+ cream（奶油）= 冰激凌！夏天最好吃的~", unit:5, required:true },
  { en:"little", zh:"少许；一点", emoji:"🤏", tip:"little = 一点/少许，a little = 一点点，修饰不可数名词~", unit:5, required:true },
  { en:"dumpling", zh:"饺子；汤圆", emoji:"🥟", tip:"dumpling = 饺子！中国的传统美食，过年必吃~", unit:5 },
  { en:"tea", zh:"茶叶；茶；茶水", emoji:"🍵", tip:"tea = 茶！只有三个字母，中国人最爱喝的~", unit:5, required:true },
  { en:"hamburger", zh:"汉堡包；汉堡牛肉饼", emoji:"🍔", tip:"hamburger = 汉堡！ham + bur + ger 分三段记~", unit:5 },
  { en:"Mrs", zh:"（姓氏前）太太，夫人", emoji:"👩", tip:"Mrs = 夫人/太太，Miss（小姐）+ Mrs 一起记！", unit:5, required:true },
  { en:"coconut", zh:"椰子", emoji:"🥥", tip:"coconut = 椰子！co-co-nut 三个音节，海岛必备水果~", unit:5 },
  { en:"interesting", zh:"有趣的；有吸引力的", emoji:"🤓", tip:"interest（兴趣）+ ing = interesting！有兴趣的→ 有趣的~", unit:5, required:true },
  { en:"seed", zh:"种子；籽", emoji:"🌱", tip:"seed = 种子！种下去会长出植物的小种子~", unit:5 },
  { en:"pull", zh:"拔出；抽出", emoji:"🔄", tip:"pull = 拉/拔！和 push（推）相反！pull up = 拔出来~", unit:5 },
  { en:"pull up", zh:"拔出", emoji:"🌿", tip:"pull（拉）+ up（向上）= 拔出来！pull up the carrot~", unit:5 },
  { en:"stem", zh:"（花草的）茎；梗", emoji:"🌿", tip:"stem = 茎/梗，植物的'身体'部分~", unit:5 },
  { en:"root", zh:"根；根茎", emoji:"🪴", tip:"root = 根！植物在地下看不见的部分就是 root~", unit:5 },
  { en:"lotus", zh:"莲属植物", emoji:"🪷", tip:"lotus = 莲花！出淤泥而不染的美丽莲花~", unit:5 },
  { en:"lake", zh:"湖；湖泊", emoji:"🏞️", tip:"lake = 湖，和 cake（蛋糕）押韵！去湖边吃蛋糕~", unit:5, required:true },
  { en:"world", zh:"世界；地球", emoji:"🌍", tip:"world = 世界！world map = 世界地图！", unit:5, required:true },
  { en:"round", zh:"圆形的；环形的；球形的", emoji:"⚪", tip:"round = 圆的！round table = 圆桌~", unit:5 },
  { en:"different", zh:"不同的；有区别的", emoji:"🌈", tip:"different = 不同的！和 same（相同）相反！", unit:5 },
  { en:"way", zh:"方法；手段；途径", emoji:"🛤️", tip:"way = 方法/路！This way = 这边走！只有三个字母~", unit:5, required:true },

  // ==================== Unit 6: Nature and Us 自然与我们 ====================
  { en:"river", zh:"河；江", emoji:"🏞️", tip:"river = 河流，音似'瑞文'→ 河流像瑞丽的文章一样流畅~", unit:6, required:true },
  { en:"nature", zh:"自然界；大自然", emoji:"🌍", tip:"nature = 自然，na-ture 两个音节，大自然就是 nature！", unit:6 },
  { en:"waterfall", zh:"瀑布", emoji:"🌊", tip:"water（水）+ fall（落下）= 瀑布！水落下来→ 瀑布！", unit:6 },
  { en:"forest", zh:"森林；林区", emoji:"🌳", tip:"forest = 森林，fore（前面）+ st → 前面一大片就是森林！", unit:6, required:true },
  { en:"famous", zh:"著名的；出名的", emoji:"🌟", tip:"famous = 出名！fame（名气）的形容词，大家都认识你~", unit:6, required:true },
  { en:"mountain", zh:"山岳；高山", emoji:"⛰️", tip:"mountain = 山，mount（攀登）+ ain → 要攀登的高山！", unit:6 },
  { en:"trip", zh:"短途旅行；出行", emoji:"🧳", tip:"trip = 旅行/出行，take a trip = 出游！", unit:6 },
  { en:"dangerous", zh:"有危险的；不安全的", emoji:"⚠️", tip:"danger（危险）+ ous = dangerous！危险的！注意安全！", unit:6 },
  { en:"heavy", zh:"程度大的；严重的", emoji:"🏋️", tip:"heavy = 重的/程度大的！heavy rain = 大雨~", unit:6, required:true },
  { en:"hotel", zh:"旅馆；旅社", emoji:"🏨", tip:"hotel = 旅馆，旅行 stay in a hotel~", unit:6 },
  { en:"close", zh:"关；关闭；闭上", emoji:"🚪", tip:"close = 关，和 open（开）相反！close the door = 关门~", unit:6, required:true },
  { en:"umbrella", zh:"伞；雨伞", emoji:"☂️", tip:"umbrella = 雨伞！um-brel-la 三个音节，下雨天必备~", unit:6, required:true },
  { en:"raincoat", zh:"雨衣", emoji:"🧥", tip:"rain（雨）+ coat（外套）= 雨衣！下雨天穿的外套~", unit:6 },
  { en:"worry", zh:"担心；担忧；发愁", emoji:"😟", tip:"worry = 担心，Don't worry! = 别担心！", unit:6, required:true },
  { en:"fine", zh:"晴朗的", emoji:"☀️", tip:"fine = 晴朗/好！It's fine today = 今天天气好~", unit:6, required:true },
  { en:"fog", zh:"雾", emoji:"🌫️", tip:"fog = 雾！只有三个字母，foggy day = 雾天~", unit:6 },
  { en:"flood", zh:"洪水；水灾", emoji:"🌊", tip:"flood = 洪水，水太多了就 flood！和大自然有关~", unit:6, required:true },
  { en:"fire", zh:"火；火灾", emoji:"🔥", tip:"fire = 火！firefighter = 消防员，灭火的人~", unit:6, required:true },
  { en:"know", zh:"知道；了解", emoji:"🧠", tip:"know = 知道，k 不发音！I know = 我知道！", unit:6, required:true },
  { en:"before", zh:"在……之前", emoji:"⏪", tip:"before = 在…之前，和 after（之后）相反！", unit:6, required:true },
  { en:"go hiking", zh:"徒步旅行", emoji:"🥾", tip:"go hiking = 徒步/远足！go + 动词 ing 表示去做某事~", unit:6 },
  { en:"bring", zh:"带来；取来", emoji:"🎒", tip:"bring = 带来，和 take（带走）相反！bring me = 带给我~", unit:6, required:true }
];